openapi: 3.0.0
info:
  title: Code Signing
  version: 1.0.0
  description: All things code signing related
servers:
  - url: http://localhost:8000/v1/
    description: Local development server
  - url: http://localhost:8000/v1/
    description: Production server
paths:
  /ehlo:
    get:
      operationId: getServerStatus
      summary: Health and wellness probe
      description: |-
        This endpoint can be used to check that the server is
        alive and well.
      tags:
        - health
      responses:
        200:
          description: The server is OK.
  /sign:
    post:
      operationId: postNewJob
      summary: Submit a package for signing
      description: |-
        Use this endpoint to submit an xcarchive, ipa or apk for
        processing. Packages can be for iOS or Android. When submiting an
        xcarchive, ensure it is ZIPed and contains a file called `options.plist`
        with all necessary export options.
      tags:
        - sign
      parameters:
        - name: platform
          in: path
          required: true
          schema:
            type: string
            enum: 
              - ios
              - android
      responses:
        200:
          description: The archive was accepted for signing
          content:
            applicaiton/json:
              schema:
                $ref: '#/components/schemas/JobReciept'
        401:
          description: You have not supplied a valid JWT
        500:
          description: Internal Error
  /sign/{jobId}/status:
    get:
      operationId: getJobStatus
      summary: Check the status of a job
      description: |-
        When a job is submitted for signing it may take several minutes for
        processing to complete. This endpoint can be used to check the status
        of the job, determine run time for the job, and get the delivery URL 
        onces processing completes.
      tags:
        - sign
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: The job has completed processing
          content:
            applicaiton/json:
              schema:
                type: object
                $ref: '#/components/schemas/Status'
        202:
          description: The job is not yet finished
        401:
          description: You have not supplied a valid JWT
        500:
          description: Internal Error
  /deploy:
    post:
      operationId: postNewJob
      summary: Specify a signed package for deployment
      description: |-
        Use this endpoint to specify a signed package from the signing jobs to deploy to AirWtch, 
        Google Play Store or App Store.
      tags:
        - deploy
      parameters:
        - name: platform
          in: path
          required: true
          schema:
            type: string
            enum: 
              - ios
              - android
      responses:
        200:
          description: The package was deployed
          content:
            applicaiton/json:
              schema:
                $ref: '#/components/schemas/JobReciept'
        401:
          description: You have not supplied a valid JWT
        500:
          description: Internal Error
components:
  schemas:
    JobReciept:
      title: Job Reciept
      type: object
      properties: 
        id: 
          type: string
      example:
        id: 'rynjE6Tl7'
    Status:
      title: Job Status
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        durationInSeconds:
          type: number
          format: float
      example:
        id: 'rynjE6Tl7'
        url: 'http://localhost:8000/v1/sign/rynjE6Tl7/download'
        durationInSeconds: '123.45'
